# Generated by Django 3.1.7 on 2021-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top25travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('images', models.CharField(max_length=255)),
            ],
        ),
    ]
